env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  indent:
    - warn
    - 4
  linebreak-style:
    - warn
    - unix
  quotes:
    - warn
    - single
  semi:
    - error
  no-console:
    - off
